### ISSUE TITLE
react-tools v0.12 update

### ISSUE THREAD

**Issue by tameraydin** [omakasecorp/gulp-jsxcs#8]
I have same the issue that is explained [here](https://github.com/orktes/node-jsxcs/issues/5).
> In React 0.12.0, [the JSX pragma is gone](http://facebook.github.io/react/blog/2014/10/16/react-v0.12-rc1.html#the-jsx-pragma-is-gone).

Would you also consider to update react-tools version?
Thanks.

**Comment by agschwender** [comment]
OK, updated in af68193f682fe120ec8c9ce30c2f583eb745f71f

**Comment by tameraydin** [comment]
Thanks
